function init(){
    var answer =  document.getElementById("euler2");
    answer.innerHTML = euler2_answer();
}

/* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. 

Steps: 
1. Make an array that resembles the terms in the Fibonacci sequence that are less than 4 million. To do this, take the array [1,1], and use array.push to add values to the end of the array. We can take the last two values of the current array, calculate the next term in the array, then push it to the array and repeat until we reach our desired limit. (4 million)

2. Using the array's length, we can iterate through each value of the array, and check if it is even. If it is, we add the value of the term to a sum variable, which holds the final answer.
*/
function euler2_answer(){
    var sum = 0;
    
    var fibonacci_sequence = generate_euler2_fibonacci_sequence();

    for (var i = 0; i < fibonacci_sequence.length; i++){
        if (fibonacci_sequence[i] % 2 == 0){
            sum += fibonacci_sequence[i];
        }
    }

   return "The answer is: " + sum;
}

function generate_euler2_fibonacci_sequence(){
    var sequence = [1,1];

    while (sequence[sequence.length-1] < 4000000){
        sequence.push(sequence[sequence.length-1] + sequence[sequence.length-2]);
    }

    return sequence;
}

document = window.document;
window.onload = init;

